{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "organizr.serviceAccountName" . }}
  labels:
    {{- include "organizr.labels" . | nindent 4 }}
{{- end -}}
