{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lidarr.serviceAccountName" . }}
  labels:
{{ include "lidarr.labels" . | nindent 4 }}
{{- end -}}
