{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "medusa.serviceAccountName" . }}
  labels:
    {{- include "medusa.labels" . | nindent 4 }}
{{- end -}}
