{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jackett.serviceAccountName" . }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
{{- end -}}
