{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bazarr.serviceAccountName" . }}
  labels:
{{ include "bazarr.labels" . | nindent 4 }}
{{- end -}}
