{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transmission.serviceAccountName" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
{{- end -}}
